CREATE DATABASE eshopper CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE eshopper;

create table `order` (`id` bigint not null auto_increment, `adress` varchar(255), `city` varchar(255), `first_name` varchar(255), `last_name` varchar(255), `date` datetime(6),`phone` varchar(255), `user_id` integer not null, primary key (`id`))ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table `cart_item` (`id` bigint not null auto_increment, `product_id` integer not null,`user_id` integer not null, `quantity` integer not null, `order_id` bigint, primary key (`id`))ENGINE=InnoDB;
create table `product` (`id` integer not null auto_increment, `category` varchar(255), `gender_category` varchar(255), `img` varchar(255), `name` varchar(255), `price` bigint, primary key (`id`))ENGINE=InnoDB;
create table `users` (`id` integer not null auto_increment, `email` varchar(255), `password` varchar(255), `username` varchar(255), primary key (`id`))ENGINE=InnoDB;
alter table `cart_item` add foreign key (`order_id`) references `order` (`id`);
alter table `cart_item` add foreign key (`product_id`) references `product` (`id`);
alter table `cart_item` add foreign key (`user_id`) references `users` (`id`);
alter table `order` add foreign key (`user_id`) references `users` (`id`);

INSERT INTO `eshopper`.`users` (`email`,`password`,`username`) VALUES ('abc@gmail.com', '123456', 'user1');
INSERT INTO `eshopper`.`users` (`email`,`password`,`username`) VALUES ('xyz@gmail.com', '123456789', 'user2');

INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('pants', 'men', 'joggerPants1', 'Jogger Pants', '31');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('pants', 'men', 'chinoPants2', 'Chino Pants', '35');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('pants', 'men', 'sweetPants3', 'Sweet Pants', '39');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('pants', 'men', 'worksPanst4', 'Works Pants', '42');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('t_shirt', 'men', 'dryColorTShirt1', 'Dry Color T-Shirt', '27');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('t_shirt', 'men', 'doraemonTShirt2', 'Doraemon T-Shirt', '44');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('t_shirt', 'men', 'stripedTShirt3', 'Stripped T-Shirt', '33');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('jeans', 'men', 'slimJeans1', 'Slim Jeans', '50');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('jeans', 'men', 'skinnyJeans2', 'Skinny Jeans', '58');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('jeans', 'men', 'stretchJeans3', 'Stretch Heans', '54');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('shorts', 'men', 'chinoShorts1', 'Chino Shorts', '36');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('shorts', 'men', 'stretchShorts2', 'Stretch Shorts', '25');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('shorts', 'men', 'cottonShorts3', 'Cotton Shorts', '39');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('shorts', 'men', 'utilityShorts4', 'Utility Shorts', '42');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('jackets', 'men', 'jerseyJacket1', 'Jersey Jacket', '47');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('jackets', 'men', 'overShirtJacket2', 'Over Shirt Jacket', '45');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('jackets', 'men', 'denimTruckerJacket3', 'Denim Trucker Jacket', '44');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('jackets', 'men', 'comfortJacket4', 'Comfort Jacket', '38');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('pants', 'women', 'denimPants5', 'Deim Pants', '61');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('pants', 'women', 'stretchPants6', 'Stretch Pants', '54');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('pants', 'women', 'heattechPants7', 'Heattech Pants', '46');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('pants', 'women', 'sweetPants8', 'Sweet Pants', '37');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('jeans', 'women', 'baggyJeans5', 'Baggy Jeans', '29');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('jeans', 'women', 'stretchJeans6', 'Stretch Jeans', '66');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('jeans', 'women', 'maternityJeans7', 'Maternity Jeans', '57');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('jeans', 'women', 'jBrandJeans8', 'JBrand Jeans', '23');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('t_shirt', 'women', 'uNeckTShirt5', 'U-Neck T-Shirt', '45');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('t_shirt', 'women', 'vNeckTShirt6', 'V-Neck T-Shirt', '37');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('t_shirt', 'women', 'dolmanTShirt7', 'Dolman T-Shirt', '64');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('t_shirt', 'women', 'cottonTShirt8', 'Cotton T-Shirt', '47');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('jackets', 'women', 'fluffyJacket5', 'Fluffy Jacker', '60');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('jackets', 'women', 'compactJacket6', 'Compact Jacket', '57');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('jackets', 'women', 'jerseyJacket7', 'Jersey Jacket', '55');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('jackets', 'women', 'denimJacket8', 'Deim Jacket', '77');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('shorts', 'women', 'linenCottonShorts5', 'Linen Cotton Shorts', '33');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('shorts', 'women', 'bikerShorts6', 'Biker Shorts', '43');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('shorts', 'women', 'cottonShorts7', 'Cotton Shorts', '56');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('skirts', 'women', 'satinSkirt1', 'Statin Skirt', '62');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('skirts', 'women', 'narrowSkirt2', 'Narrow Skirt', '52');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('skirts', 'women', 'longSkirt3', 'Long Skirt', '34');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('tops', 'baby', 'sweatShirtB1', 'Sweat Shirt', '24');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('tops', 'baby', 'mickeyTShirtB2', 'Mickey T-Shirt', '27');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('tops', 'baby', 'fleecePulloverB3', 'Fleece Pullover', '29');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('tops', 'baby', 'disneyTShirtB4', 'Disney T-Shirt', '33');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('bottoms', 'baby', 'knittedLeggingsB5', 'Knightted Leggings', '32');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('bottoms', 'baby', 'relaxedLeggingsB6', 'Relaxed Leggings', '38');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('bottoms', 'baby', 'fleeceLeggingsB7', 'Fleece Leggings', '42');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('bottoms', 'baby', 'heattechLeggingsB8', 'Heattech Leggings', '46');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('one_pieces', 'baby', 'onepieceOutfitB9', 'Onepiece Outfit', '25');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('one_pieces', 'baby', 'kumaOutfitB10', 'Kuma Outfit', '36');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('one_pieces', 'baby', 'woodlandOutfitB11', 'Woodland Outfit', '54');
INSERT INTO `eshopper`.`product` (`category`, `gender_category`, `img`, `name`, `price`) VALUES ('one_pieces', 'baby', 'rabbitOutfitB12', 'Rabbit Outfit', '46');
